package de.evoila.osb.checker.request.bodies

import de.evoila.osb.checker.response.catalog.Catalog
import de.evoila.osb.checker.response.catalog.Plan
import de.evoila.osb.checker.response.catalog.Service

interface SwappableServiceAndPlan<T> where T : RequestBody {

    fun serviceIdEquals(otherServiceId: String): Boolean

    fun swapServiceIdAndPlanId(service: Service): T

    fun swapPlanId(plan: Plan): T

    /*
     * To avoid accidental overwrite by autogenerated getPlan() from DataClasses.
     */
    fun extractPlanId(): String?

    fun swap(catalog: Catalog): T {
        return if (catalog.services.size > 1) {
            catalog.services.first { service -> !this.serviceIdEquals(service.id) }.let {
                this.swapServiceIdAndPlanId(it)
            }
        } else {
            this.swapPlanId(catalog.services.first().plans.first { this.extractPlanId() != it.id })
        }
    }
}